#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -config ~/.config/rofi/themes/config.simple -location 7 -xoffset 20 -yoffset -50 -line-padding 4 -columns 1 -width 20 -lines 10 -padding 25 -hide-scrollbar -show-icons -drun-icon-theme "Papirus"
