#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -config ~/.config/rofi/themes/config.simple -line-padding 4 -columns 2 -width 40 -padding 30 -hide-scrollbar -show-icons -drun-icon-theme "Papirus"

