#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -config ~/.config/rofi/themes/config.simple -sep "|" -dmenu -i -p 'System' -location 5 -yoffset -50 -xoffset -20 -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) i3lock-fancy ;;
                *Logout) openbox --exit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
